import {
  UserProfile,
  DocumentItem,
  TaskItem,
  ReportItem,
  EmailDraft,
  WorkDossier,
  NotificationItem,
  AuditLog,
  ThemeConfig,
  AiSettings,
} from './types';

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'USR-01',
    name: 'TS. Đỗ Thị Lan',
    email: 'hieutruong@thpt-ngoquyen.edu.vn',
    phone: '0912.345.678',
    role: 'HIEU_TRUONG',
    roleTitle: 'Hiệu trưởng',
    department: 'Ban Giám hiệu',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    fieldsOfWork: ['Quản trị chung', 'Nhân sự', 'Tài chính', 'Phê duyệt văn bản'],
    status: 'ACTIVE',
  },
  {
    id: 'USR-02',
    name: 'ThS. Trần Văn Hùng',
    email: 'hungtv@thpt-ngoquyen.edu.vn',
    phone: '0904.123.456',
    role: 'PHO_HIEU_TRUONG',
    roleTitle: 'Phó Hiệu trưởng',
    department: 'Ban Giám hiệu',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    fieldsOfWork: ['Chuyên môn', 'Khảo thí', 'Bồi dưỡng HSG', 'Nghiên cứu KHKT'],
    status: 'ACTIVE',
  },
  {
    id: 'USR-03',
    name: 'Cô Lê Thị Mai',
    email: 'mailt@thpt-ngoquyen.edu.vn',
    phone: '0983.888.999',
    role: 'PHO_HIEU_TRUONG',
    roleTitle: 'Phó Hiệu trưởng',
    department: 'Ban Giám hiệu',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200',
    fieldsOfWork: ['Cơ sở vật chất', 'Hoạt động trải nghiệm', 'An toàn trường học', 'Đoàn thanh niên'],
    status: 'ACTIVE',
  },
  {
    id: 'USR-04',
    name: 'Thầy Bùi Minh Đức',
    email: 'admin@thpt-ngoquyen.edu.vn',
    phone: '0936.555.666',
    role: 'SUPER_ADMIN',
    roleTitle: 'Super Admin / Quản trị hệ thống',
    department: 'Văn phòng - CNTT',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    fieldsOfWork: ['Quản trị hệ thống AI', 'Chuyển đổi số', 'Bảo mật thông tin', 'Phân quyền'],
    status: 'ACTIVE',
  },
  {
    id: 'USR-05',
    name: 'Cô Phạm Thu Hà',
    email: 'vanthu@thpt-ngoquyen.edu.vn',
    phone: '0915.222.333',
    role: 'VAN_THU',
    roleTitle: 'Cán bộ Văn thư',
    department: 'Văn phòng',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200',
    fieldsOfWork: ['Tiếp nhận văn bản', 'Số hóa hồ sơ', 'Phát hành văn bản đi', 'Quản lý con dấu'],
    status: 'ACTIVE',
  },
  {
    id: 'USR-06',
    name: 'Cô Hoàng Thị Thảo',
    email: 'ketoan@thpt-ngoquyen.edu.vn',
    phone: '0977.111.222',
    role: 'KE_TOAN',
    roleTitle: 'Kế toán trưởng',
    department: 'Tài chính - Kế toán',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&q=80&w=200',
    fieldsOfWork: ['Tài chính', 'Dự toán ngân sách', 'Chế độ giáo viên', 'Thanh quyết toán'],
    status: 'ACTIVE',
  },
  {
    id: 'USR-07',
    name: 'Thầy Nguyễn Văn Tuấn',
    email: 'tuanmath@thpt-ngoquyen.edu.vn',
    phone: '0988.333.444',
    role: 'TO_TRUONG',
    roleTitle: 'Tổ trưởng chuyên môn',
    department: 'Tổ Toán - Tin học',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    fieldsOfWork: ['Chuyên môn Toán - Tin', 'Bồi dưỡng HSG', 'Thi Olympic', 'Phân công chuyên môn'],
    status: 'ACTIVE',
  },
  {
    id: 'USR-08',
    name: 'Cô Vũ Thị Hoài',
    email: 'hoaivan@thpt-ngoquyen.edu.vn',
    phone: '0918.444.555',
    role: 'TO_TRUONG',
    roleTitle: 'Tổ trưởng chuyên môn',
    department: 'Tổ Ngữ văn',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    fieldsOfWork: ['Chuyên môn Ngữ văn', 'CLB Sách & Văn học', 'Bồi dưỡng HSG Văn'],
    status: 'ACTIVE',
  },
  {
    id: 'USR-09',
    name: 'Cô Trần Mai Loan',
    email: 'loantm@thpt-ngoquyen.edu.vn',
    phone: '0944.666.777',
    role: 'GV_CHU_NHIEM',
    roleTitle: 'Giáo viên & GVCN 11A1',
    department: 'Tổ Ngữ văn',
    avatar: 'https://images.unsplash.com/photo-1548142813-c348350df52b?auto=format&fit=crop&q=80&w=200',
    fieldsOfWork: ['Giảng dạy Ngữ văn', 'Công tác chủ nhiệm 11A1', 'Tư vấn tâm lý học đường'],
    status: 'ACTIVE',
  },
  {
    id: 'USR-10',
    name: 'Thầy Đặng Quốc Bảo',
    email: 'baodq@thpt-ngoquyen.edu.vn',
    phone: '0922.777.888',
    role: 'TO_TRUONG',
    roleTitle: 'Tổ trưởng chuyên môn',
    department: 'Tổ KHTN (Lý - Hóa - Sinh)',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200',
    fieldsOfWork: ['Chuyên môn Vật lý, Hóa học, Sinh học', 'Phòng thực hành thí nghiệm', 'STEM/STEAM'],
    status: 'ACTIVE',
  },
];

export const INITIAL_DOCUMENTS: DocumentItem[] = [
  {
    id: 'DOC-2026-001',
    documentNumber: '186/SGDĐT-GDTrH',
    title: 'V/v Hướng dẫn triển khai công tác giáo dục hướng nghiệp và định hướng phân luồng học sinh THPT năm học 2026-2027',
    issuingAgency: 'Sở Giáo dục và Đào tạo TP. Hải Phòng',
    signer: 'Nguyễn Đình Vinh',
    signerTitle: 'Phó Giám đốc Sở',
    issueDate: '2026-09-02',
    effectiveDate: '2026-09-05',
    deadline: '2026-09-25',
    urgency: 'Khẩn',
    confidentiality: 'Thường',
    status: 'Chờ BGH duyệt',
    summary: 'Sở GD&ĐT chỉ đạo các trường THPT xây dựng kế hoạch tư vấn nghề nghiệp, kết nối doanh nghiệp và trường đại học, tổ chức ngày hội hướng nghiệp cho học sinh khối 11, 12 và báo cáo tiến độ về Sở trước ngày 25/09/2026.',
    legalReferences: [
      'Luật Giáo dục năm 2019',
      'Quyết định số 522/QĐ-TTg của Thủ tướng Chính phủ phê duyệt Đề án GDHN và phân luồng',
      'Công văn số 4020/BGDĐT-GDTrH của Bộ GD&ĐT',
    ],
    recipients: [
      'Các trường THPT, trường Phổ thông nhiều cấp học',
      'Trung tâm GDTX-HN',
      'Phòng GDTrH - Sở GDĐT Hải Phòng',
    ],
    attachments: [
      'CV_186_Huong_nghiep_2026.pdf',
      'Phu_luc_Ke_hoach_mau.docx',
      'Mau_Bao_cao_so_lieu.xlsx',
    ],
    reportingRequirements: 'Nộp báo cáo kế hoạch và danh mục chuyên đề trải nghiệm nghề nghiệp trước 17h00 ngày 25/09/2026.',
    version: 'V1',
    docType: 'Văn bản đến',
    createdAt: '2026-09-03T08:30:00Z',
    advisorySheet: {
      documentId: 'DOC-2026-001',
      documentNumber: '186/SGDĐT-GDTrH',
      aiSummary: 'Văn bản quy định bắt buộc các trường THPT thành lập Ban tư vấn hướng nghiệp năm học 2026-2027, xây dựng chương trình tối thiểu 12 tiết trải nghiệm thực tế và tổ chức khảo sát nguyện vọng học sinh lớp 12.',
      keyRequirements: '1. Thành lập Ban tư vấn hướng nghiệp cấp trường.\n2. Phối hợp với Đoàn thanh niên tổ chức Ngày hội Hướng nghiệp.\n3. Tổng hợp số liệu nguyện vọng của 100% học sinh khối 12.',
      deadline: '2026-09-25',
      status: 'Chờ duyệt',
      proposedOwner: 'Cô Lê Thị Mai (Phó Hiệu trưởng)',
      outputProduct: 'Kế hoạch tư vấn hướng nghiệp cấp trường và Báo cáo số liệu gửi Sở GDĐT',
      tasks: [
        {
          taskId: 'NV-HN01',
          title: 'Soạn thảo Quyết định kiện toàn Ban tư vấn hướng nghiệp và phân luồng năm học 2026-2027',
          description: 'Rà soát danh sách thành viên gồm BGH, Đoàn trường, GVCN khối 12, đại diện Ban đại diện CMHS để trình Hiệu trưởng ký.',
          owner: 'Cô Lê Thị Mai (Phó Hiệu trưởng)',
          collaborators: ['Phạm Thu Hà (Văn thư)', 'Bí thư Đoàn trường'],
          approver: 'TS. Đỗ Thị Lan (Hiệu trưởng)',
          deadline: '2026-09-15',
          priority: 'Cao',
          outputRequired: 'Quyết định thành lập Ban tư vấn (kèm danh sách phân công)',
          reportReceiver: 'Hiệu trưởng',
          evidence: 'Quyết định có số hiệu và chữ ký',
          confidence: 0.98,
        },
        {
          taskId: 'NV-HN02',
          title: 'Khảo sát nhu cầu ngành nghề và xu hướng chọn trường của học sinh khối 12',
          description: 'Xây dựng form khảo sát trực tuyến, hướng dẫn GVCN triển khai trong tiết sinh hoạt lớp và trích xuất bảng phân tích dữ liệu.',
          owner: 'Cô Trần Mai Loan (GVCN 11A1 & GV Ngữ văn)',
          collaborators: ['Thầy Bùi Minh Đức (CNTT)', 'GVCN khối 12'],
          approver: 'ThS. Trần Văn Hùng (Phó Hiệu trưởng)',
          deadline: '2026-09-20',
          priority: 'Trung bình',
          outputRequired: 'Báo cáo phân tích số liệu khảo sát (File Excel + Biểu đồ PowerPoint)',
          reportReceiver: 'Ban Giám hiệu',
          evidence: 'Dữ liệu phản hồi form và báo cáo đồ thị',
          confidence: 0.94,
        },
        {
          taskId: 'NV-HN03',
          title: 'Tổng hợp Báo cáo kế hoạch hướng nghiệp của trường nộp về Sở GD&ĐT Hải Phòng',
          description: 'Tổng hợp sản phẩm của các tổ và ban tư vấn, hoàn thiện báo cáo chính thức nộp trực tuyến trước 17h00 ngày 25/09.',
          owner: 'Cô Phạm Thu Hà (Văn thư)',
          collaborators: ['Cô Lê Thị Mai (PHT)', 'Hoàng Thị Thảo (Kế toán)'],
          approver: 'TS. Đỗ Thị Lan (Hiệu trưởng)',
          deadline: '2026-09-25',
          priority: 'Khẩn cấp',
          outputRequired: 'Văn bản báo cáo chính thức gửi Sở GDĐT có số công văn đi',
          reportReceiver: 'Sở Giáo dục và Đào tạo Hải Phòng',
          evidence: 'Văn bản phát hành ký số gửi qua iOffice',
          confidence: 0.97,
        },
      ],
      draftEmail: {
        subject: '[NQ OFFICE AI] Chỉ đạo thực hiện Công văn 186/SGDĐT về công tác hướng nghiệp năm học 2026-2027',
        body: 'Kính gửi: Các Thầy/Cô trong Ban Giám hiệu, Đoàn Thanh niên và các Tổ trưởng chuyên môn,\n\nBan Giám hiệu Trường THPT Ngô Quyền gửi thông báo phân công nhiệm vụ triển khai công tác giáo dục hướng nghiệp theo CV 186/SGDĐT.\nĐề nghị PHT Lê Thị Mai chủ trì, Văn phòng và GVCN các lớp phối hợp triển khai nghiêm túc, cập nhật tiến độ trên phần mềm NQ Office AI.\n\nTrân trọng,\nTS. Đỗ Thị Lan - Hiệu trưởng',
      },
    },
  },
  {
    id: 'DOC-2026-002',
    documentNumber: '4020/BGDĐT-GDTrH',
    title: 'Hướng dẫn thực hiện nhiệm vụ giáo dục trung học năm học 2026-2027',
    issuingAgency: 'Bộ Giáo dục và Đào tạo',
    signer: 'Nguyễn Văn Phúc',
    signerTitle: 'Thứ trưởng',
    issueDate: '2026-08-28',
    effectiveDate: '2026-09-01',
    deadline: '2026-09-30',
    urgency: 'Thượng khẩn',
    confidentiality: 'Thường',
    status: 'Đang thực hiện',
    summary: 'Chỉ đạo toàn diện các hoạt động dạy học, đổi mới phương pháp kiểm tra đánh giá theo Chương trình GDPT 2018, tăng cường giáo dục STEM, chuyển đổi số và nâng cao năng lực ngoại ngữ cho học sinh THPT.',
    legalReferences: [
      'Nghị quyết số 29-NQ/TW về đổi mới căn bản, toàn diện giáo dục',
      'Thông tư 32/2018/TT-BGDĐT',
      'Thông tư 22/2021/TT-BGDĐT về đánh giá học sinh THCS và THPT',
    ],
    recipients: [
      'Các Sở GD&ĐT trên toàn quốc',
      'Các trường THPT chuyên và THPT trực thuộc',
    ],
    attachments: ['HD_4020_Nhiem_vu_nam_hoc_2026_2027.pdf'],
    version: 'V2',
    docType: 'Văn bản đến',
    createdAt: '2026-08-30T10:00:00Z',
  },
  {
    id: 'DOC-2026-003',
    documentNumber: '128/SGDĐT-VP',
    title: 'V/v Đẩy mạnh triển khai hệ thống văn phòng số và bảo đảm an toàn thông tin mạng trong các cơ sở giáo dục',
    issuingAgency: 'Sở Giáo dục và Đào tạo TP. Hải Phòng',
    signer: 'Bùi Văn Kiệm',
    signerTitle: 'Giám đốc Sở',
    issueDate: '2026-09-05',
    deadline: '2026-09-18',
    urgency: 'Hỏa tốc',
    confidentiality: 'Thường',
    status: 'Đã duyệt & giao việc',
    summary: 'Yêu cầu 100% cán bộ quản lý và giáo viên sử dụng văn phòng điện tử, ký số cá nhân và tuân thủ các quy định về an toàn an ninh dữ liệu học sinh.',
    legalReferences: ['Nghị định 42/2022/NĐ-CP về cung cấp thông tin và dịch vụ công trực tuyến'],
    recipients: ['Các cơ sở giáo dục trên toàn thành phố Hải Phòng'],
    attachments: ['CV_128_An_toan_thong_tin_mang.pdf'],
    version: 'FINAL',
    docType: 'Văn bản đến',
    createdAt: '2026-09-06T09:15:00Z',
  },
  {
    id: 'DOC-2026-004',
    documentNumber: '215/BC-THPTNQ',
    title: 'Báo cáo tình hình chuẩn bị năm học mới 2026-2027 và triển khai các điều kiện giảng dạy',
    issuingAgency: 'Trường THPT Ngô Quyền',
    signer: 'Đỗ Thị Lan',
    signerTitle: 'Hiệu trưởng',
    issueDate: '2026-09-04',
    urgency: 'Bình thường',
    confidentiality: 'Thường',
    status: 'Hoàn thành',
    summary: 'Báo cáo chính thức của Trường THPT Ngô Quyền gửi Sở GD&ĐT Hải Phòng về cơ sở vật chất, đội ngũ 105 cán bộ giáo viên và phương án đón 1.850 học sinh tựu trường.',
    legalReferences: ['Công văn 4020/BGDĐT-GDTrH'],
    recipients: ['Sở Giáo dục và Đào tạo Hải Phòng', 'UBND Quận Lê Chân', 'Lưu: VT, BGH'],
    attachments: ['BC_215_THPT_Ngo_Quyen_Khai_giang.pdf'],
    version: 'FINAL',
    docType: 'Văn bản đi',
    relatedDocId: 'DOC-2026-002',
    createdAt: '2026-09-04T14:00:00Z',
  },
];

export const INITIAL_TASKS: TaskItem[] = [
  {
    id: 'TSK-001',
    code: 'NV-HN01',
    title: 'Soạn thảo Quyết định kiện toàn Ban tư vấn hướng nghiệp năm học 2026-2027',
    description: 'Chủ trì soạn thảo Quyết định thành lập Ban tư vấn hướng nghiệp và phân luồng, lấy ý kiến các tổ và trình Hiệu trưởng ký ban hành.',
    sourceDocId: 'DOC-2026-001',
    sourceDocNumber: '186/SGDĐT-GDTrH',
    owner: 'Cô Lê Thị Mai',
    ownerId: 'USR-03',
    department: 'Ban Giám hiệu',
    collaborators: ['Phạm Thu Hà (Văn thư)', 'Bí thư Đoàn trường'],
    approver: 'TS. Đỗ Thị Lan (Hiệu trưởng)',
    assignDate: '2026-09-06',
    deadline: '2026-09-15',
    outputRequired: 'Quyết định thành lập Ban tư vấn (kèm danh sách phân công nhiệm vụ)',
    evidenceFiles: ['QD_Kien_toan_Ban_Huong_nghiep.docx'],
    priority: 'Cao',
    progress: 75,
    status: 'ĐANG LÀM',
    comments: [
      {
        id: 'CMT-1',
        author: 'Cô Lê Thị Mai',
        role: 'Phó Hiệu trưởng',
        timestamp: '2026-09-07 10:20',
        content: 'Đã hoàn thành dự thảo danh sách 15 thành viên, đang chờ xác nhận từ Đoàn thanh niên.',
      },
    ],
    history: ['Khởi tạo từ Phiếu tham mưu AI', 'Hiệu trưởng duyệt và phân công ngày 06/09/2026'],
  },
  {
    id: 'TSK-002',
    code: 'NV-HN02',
    title: 'Khảo sát nhu cầu ngành nghề và xu hướng chọn trường của học sinh khối 12',
    description: 'Xây dựng form khảo sát trực tuyến, hướng dẫn GVCN triển khai trong tiết sinh hoạt lớp và trích xuất bảng phân tích dữ liệu.',
    sourceDocId: 'DOC-2026-001',
    sourceDocNumber: '186/SGDĐT-GDTrH',
    owner: 'Cô Trần Mai Loan',
    ownerId: 'USR-09',
    department: 'Tổ Ngữ văn',
    collaborators: ['Thầy Bùi Minh Đức (CNTT)', 'GVCN khối 12'],
    approver: 'ThS. Trần Văn Hùng (Phó Hiệu trưởng)',
    assignDate: '2026-09-06',
    deadline: '2026-09-20',
    outputRequired: 'Báo cáo phân tích số liệu khảo sát (File Excel + Biểu đồ PowerPoint)',
    evidenceFiles: [],
    priority: 'Trung bình',
    progress: 40,
    status: 'ĐANG LÀM',
    comments: [],
    history: ['Phân công theo chỉ đạo BGH'],
  },
  {
    id: 'TSK-003',
    code: 'NV-CM01',
    title: 'Xây dựng kế hoạch dạy học các môn học và hoạt động giáo dục theo tổ chuyên môn',
    description: 'Các tổ chuyên môn tổ chức sinh hoạt, thống nhất phân phối chương trình, xây dựng ma trận đề kiểm tra đánh giá định kỳ.',
    sourceDocId: 'DOC-2026-002',
    sourceDocNumber: '4020/BGDĐT-GDTrH',
    owner: 'Thầy Nguyễn Văn Tuấn',
    ownerId: 'USR-07',
    department: 'Tổ Toán - Tin học',
    collaborators: ['Vũ Thị Hoài (Văn)', 'Trần Minh Phương (Anh)', 'Đặng Quốc Bảo (KHTN)'],
    approver: 'ThS. Trần Văn Hùng (Phó Hiệu trưởng)',
    assignDate: '2026-09-01',
    deadline: '2026-09-12',
    outputRequired: 'Kế hoạch dạy học đã được phê duyệt và biên bản sinh hoạt tổ',
    evidenceFiles: ['Ke_hoach_day_hoc_Toan_Tin_HK1.docx', 'Bien_ban_sinh_hoat_to_1.pdf'],
    priority: 'Khẩn cấp',
    progress: 90,
    status: 'CHỜ KIỂM TRA',
    comments: [
      {
        id: 'CMT-2',
        author: 'Thầy Nguyễn Văn Tuấn',
        role: 'Tổ trưởng Toán - Tin',
        timestamp: '2026-09-08 14:15',
        content: 'Tổ Toán - Tin đã nộp đủ biên bản và phân phối chương trình môn Toán khối 10, 11, 12.',
      },
    ],
    history: ['Nộp sản phẩm lên BGH thẩm định'],
  },
  {
    id: 'TSK-004',
    code: 'NV-IT01',
    title: 'Kiểm tra an toàn thông tin và kích hoạt chữ ký số cho 100% cán bộ giáo viên',
    description: 'Rà soát chứng thư số công vụ, cài đặt phần mềm ký số trên NQ Office AI và kiểm tra xác thực hai lớp.',
    sourceDocId: 'DOC-2026-003',
    sourceDocNumber: '128/SGDĐT-VP',
    owner: 'Thầy Bùi Minh Đức',
    ownerId: 'USR-04',
    department: 'Văn phòng - CNTT',
    collaborators: ['Phạm Thu Hà (Văn thư)', 'Tất cả giáo viên'],
    approver: 'TS. Đỗ Thị Lan (Hiệu trưởng)',
    assignDate: '2026-09-06',
    deadline: '2026-09-18',
    outputRequired: 'Danh sách 105/105 cán bộ giáo viên đã kích hoạt chữ ký số và tài khoản',
    evidenceFiles: ['Danh_sach_chu_ky_so_THPT_Ngo_Quyen.xlsx'],
    priority: 'Cao',
    progress: 100,
    status: 'HOÀN THÀNH',
    comments: [],
    history: ['Nhiệm vụ đã hoàn thành xuất sắc trước hạn'],
  },
  {
    id: 'TSK-005',
    code: 'NV-HN03',
    title: 'Tổng hợp Báo cáo kế hoạch hướng nghiệp của trường nộp về Sở GD&ĐT Hải Phòng',
    description: 'Tổng hợp sản phẩm của các tổ và ban tư vấn, hoàn thiện báo cáo chính thức nộp trực tuyến trước 17h00 ngày 25/09.',
    sourceDocId: 'DOC-2026-001',
    sourceDocNumber: '186/SGDĐT-GDTrH',
    owner: 'Cô Phạm Thu Hà',
    ownerId: 'USR-05',
    department: 'Văn phòng',
    collaborators: ['Cô Lê Thị Mai (PHT)', 'Hoàng Thị Thảo (Kế toán)'],
    approver: 'TS. Đỗ Thị Lan (Hiệu trưởng)',
    assignDate: '2026-09-06',
    deadline: '2026-09-25',
    outputRequired: 'Văn bản báo cáo chính thức gửi Sở GDĐT có số công văn đi',
    evidenceFiles: [],
    priority: 'Khẩn cấp',
    progress: 15,
    status: 'ĐÃ GIAO',
    comments: [],
    history: ['Chờ dữ liệu từ Ban tư vấn hướng nghiệp'],
  },
  {
    id: 'TSK-006',
    code: 'NV-CB01',
    title: 'Bổ sung danh sách học sinh diện chính sách và miễn giảm học phí học kỳ I',
    description: 'Rà soát giấy tờ xác nhận hộ nghèo, con thương binh liệt sĩ để kế toán lập hồ sơ hỗ trợ chi phí học tập.',
    owner: 'Cô Hoàng Thị Thảo',
    ownerId: 'USR-06',
    department: 'Tài chính - Kế toán',
    collaborators: ['GVCN khối 10, 11, 12'],
    approver: 'TS. Đỗ Thị Lan (Hiệu trưởng)',
    assignDate: '2026-08-25',
    deadline: '2026-09-05',
    outputRequired: 'Danh sách tổng hợp và hồ sơ minh chứng công chứng',
    evidenceFiles: ['Danh_sach_dien_chinh_sach_HK1.xlsx'],
    priority: 'Cao',
    progress: 80,
    status: 'QUÁ HẠN',
    comments: [
      {
        id: 'CMT-3',
        author: 'Cô Hoàng Thị Thảo',
        role: 'Kế toán trưởng',
        timestamp: '2026-09-06 08:30',
        content: 'Còn 3 học sinh lớp 10 chưa nộp giấy xác nhận xã phường, đang đôn đốc GVCN.',
      },
    ],
    history: ['Cảnh báo tự động gửi qua Notification & Email'],
  },
];

export const INITIAL_REPORTS: ReportItem[] = [
  {
    id: 'RPT-01',
    code: 'BC-TUAN-01',
    title: 'Báo cáo công tác điều hành tuần 1 tháng 9/2026 - Trường THPT Ngô Quyền',
    type: 'Hàng tuần',
    period: 'Tuần 1 (01/09 - 07/09/2026)',
    author: 'Cô Phạm Thu Hà (Văn phòng)',
    department: 'Văn phòng',
    createdDate: '2026-09-07',
    status: 'Đã duyệt',
    content: `I. TÌNH HÌNH CHUNG
Trường THPT Ngô Quyền đã tổ chức Lễ Khai giảng năm học 2026-2027 trang trọng, an toàn và đúng quy định của Sở GD&ĐT Hải Phòng.
100% học sinh và cán bộ giáo viên tham dự đầy đủ.

II. KẾT QUẢ TRIỂN KHAI NHIỆM VỤ THEO CÔNG VĂN SỞ GD&ĐT
1. Chuyên môn:
- 7/7 tổ chuyên môn đã hoàn thành dự thảo phân phối chương trình chi tiết theo Chương trình GDPT 2018.
- Tổ chức bồi dưỡng đội tuyển HSG thành phố giai đoạn 1.
2. Công tác chuyển đổi số:
- 105/105 cán bộ giáo viên đã đăng nhập và sử dụng hệ thống văn phòng số NQ Office AI.
- Đã xử lý 14 văn bản đến và phát hành 3 văn bản đi đúng quy chuẩn.
3. Cơ sở vật chất:
- Toàn bộ 42 phòng học thông minh và 4 phòng thí nghiệm đạt chuẩn kỹ thuật.`,
    taskIds: ['TSK-001', 'TSK-003', 'TSK-004'],
    version: 'FINAL',
    checkerResult: {
      evaluation: 'Đã đáp ứng',
      score: 95,
      summary: 'Báo cáo tổng hợp số liệu rõ ràng, minh chứng đính kèm đầy đủ và đúng thời hạn theo chỉ đạo của BGH.',
      details: [
        {
          criterion: 'Nội dung khai giảng và nền nếp dạy học',
          status: 'Đã đáp ứng',
          notes: 'Đã báo cáo đầy đủ số liệu học sinh, giáo viên',
          evidenceProvided: 'Bien_ban_khai_giang.pdf',
        },
        {
          criterion: 'Tiến độ chuyên môn các tổ',
          status: 'Đã đáp ứng',
          notes: 'Tất cả 7 tổ chuyên môn đã có báo cáo phân phối chương trình',
          evidenceProvided: 'Ke_hoach_cac_to.zip',
        },
      ],
    },
  },
];

export const INITIAL_EMAIL_DRAFTS: EmailDraft[] = [
  {
    id: 'EML-01',
    to: 'mailt@thpt-ngoquyen.edu.vn',
    recipientName: 'Cô Lê Thị Mai (Phó Hiệu trưởng)',
    cc: 'hieutruong@thpt-ngoquyen.edu.vn; vanthu@thpt-ngoquyen.edu.vn',
    subject: '[NQ OFFICE AI] Giao nhiệm vụ chủ trì: Kiện toàn Ban tư vấn hướng nghiệp năm học 2026-2027',
    body: `Kính gửi Cô Lê Thị Mai - Phó Hiệu trưởng,

Căn cứ Công văn số 186/SGDĐT-GDTrH của Sở GD&ĐT Hải Phòng về công tác giáo dục hướng nghiệp, Hiệu trưởng Trường THPT Ngô Quyền phân công Cô chủ trì thực hiện nhiệm vụ:
- Tên nhiệm vụ: Soạn thảo Quyết định kiện toàn Ban tư vấn hướng nghiệp năm học 2026-2027
- Hạn nộp sản phẩm: 2026-09-15
- Sản phẩm yêu cầu: Dự thảo Quyết định có danh sách thành viên và phân công nhiệm vụ chi tiết.

Kính đề nghị Cô truy cập hệ thống NQ Office AI để tiếp nhận và cập nhật tiến độ.

Trân trọng,
BAN GIÁM HIỆU TRƯỜNG THPT NGÔ QUYỀN`,
    status: 'Đã duyệt',
    createdAt: '2026-09-06T10:00:00Z',
    sentAt: '2026-09-06T10:30:00Z',
    relatedTaskId: 'TSK-001',
    relatedDocNumber: '186/SGDĐT-GDTrH',
    reviewedBy: 'TS. Đỗ Thị Lan (Hiệu trưởng)',
  },
  {
    id: 'EML-02',
    to: 'tuanmath@thpt-ngoquyen.edu.vn',
    recipientName: 'Thầy Nguyễn Văn Tuấn (Tổ trưởng Toán - Tin)',
    subject: '[NQ OFFICE AI] Nhắc hoàn thiện kiểm tra phân phối chương trình học kỳ I',
    body: `Kính gửi Thầy Nguyễn Văn Tuấn,

Ban Giám hiệu nhắc nhở Tổ Toán - Tin học khẩn trương rà soát lại số tiết ôn tập chuyên đề khối 12 trước ngày 12/09/2026 để PHT Trần Văn Hùng ký phê duyệt.

Trân trọng,
Ban Giám hiệu Trường THPT Ngô Quyền`,
    status: 'Chờ duyệt',
    createdAt: '2026-09-08T09:00:00Z',
    relatedTaskId: 'TSK-003',
  },
];

export const INITIAL_DOSSIERS: WorkDossier[] = [
  {
    id: 'DOS-2026-01',
    code: 'HS-HN-2026',
    title: 'Hồ sơ Công tác Giáo dục hướng nghiệp và phân luồng học sinh năm học 2026-2027',
    schoolYear: '2026-2027',
    department: 'Ban Tư vấn Hướng nghiệp',
    createdDate: '2026-09-03',
    status: 'Đang xử lý',
    documents: [
      { id: 'DOC-2026-001', number: '186/SGDĐT-GDTrH', title: 'Hướng dẫn triển khai công tác giáo dục hướng nghiệp' },
    ],
    tasks: [
      { id: 'TSK-001', code: 'NV-HN01', title: 'Kiện toàn Ban tư vấn hướng nghiệp', status: 'ĐANG LÀM' },
      { id: 'TSK-002', code: 'NV-HN02', title: 'Khảo sát nhu cầu ngành nghề khối 12', status: 'ĐANG LÀM' },
      { id: 'TSK-005', code: 'NV-HN03', title: 'Báo cáo nộp Sở GDĐT', status: 'ĐÃ GIAO' },
    ],
    emails: [
      { id: 'EML-01', subject: 'Giao nhiệm vụ chủ trì: Kiện toàn Ban tư vấn hướng nghiệp', sentAt: '2026-09-06 10:30' },
    ],
    submittedFiles: [
      { name: 'QD_Kien_toan_Ban_Huong_nghiep.docx', uploadedBy: 'Cô Lê Thị Mai', date: '2026-09-07', size: '420 KB' },
    ],
    minutes: ['Biên bản họp BGH ngày 05/09/2026 về định hướng nghề nghiệp'],
    reports: ['Dự thảo Báo cáo hướng nghiệp THPT Ngô Quyền'],
    outgoingDocs: ['Dự thảo CV gửi Sở GDĐT'],
    history: ['Khởi tạo hồ sơ tự động từ AI Document Intelligence khi tiếp nhận CV 186/SGDĐT'],
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'NOTIF-01',
    title: 'Công văn mới cần tham mưu',
    content: 'Văn thư đã tiếp nhận Công văn số 186/SGDĐT-GDTrH về Hướng dẫn giáo dục hướng nghiệp.',
    type: 'Văn bản mới',
    createdAt: '15 phút trước',
    read: false,
    targetId: 'DOC-2026-001',
    targetType: 'doc',
  },
  {
    id: 'NOTIF-02',
    title: 'Yêu cầu phê duyệt Phiếu tham mưu xử lý',
    content: 'AI đã trích xuất 3 nhiệm vụ cho CV 186/SGDĐT-GDTrH. Đang chờ Hiệu trưởng xem xét và phê duyệt.',
    type: 'Yêu cầu duyệt',
    createdAt: '1 giờ trước',
    read: false,
    targetId: 'DOC-2026-001',
    targetType: 'doc',
  },
  {
    id: 'NOTIF-03',
    title: 'Nhiệm vụ sắp đến hạn (3 ngày)',
    content: 'Nhiệm vụ "Xây dựng kế hoạch dạy học các môn học" của Tổ Toán - Tin có hạn chót ngày 12/09/2026.',
    type: 'Sắp đến hạn',
    createdAt: 'Hôm nay, 08:30',
    read: true,
    targetId: 'TSK-003',
    targetType: 'task',
  },
  {
    id: 'NOTIF-04',
    title: 'Cảnh báo quá hạn xử lý',
    content: 'Nhiệm vụ "Bổ sung danh sách học sinh diện chính sách" đã quá hạn từ ngày 05/09/2026.',
    type: 'Quá hạn',
    createdAt: 'Hôm qua',
    read: false,
    targetId: 'TSK-006',
    targetType: 'task',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'AUD-001',
    timestamp: '2026-09-09 08:15:20',
    user: 'Thầy Bùi Minh Đức (Super Admin)',
    role: 'SUPER_ADMIN',
    action: 'Cấu hình tham số mô hình AI',
    entity: 'AI Settings',
    entityId: 'CFG-GEMINI',
    beforeContent: 'Temperature: 0.7, Model: gemini-3.8-flash',
    afterContent: 'Temperature: 0.3, Model: gemini-3.8-flash, Automation Level: Mức 3',
    actorType: 'HUMAN',
    ipAddress: '192.168.1.10',
  },
  {
    id: 'AUD-002',
    timestamp: '2026-09-08 16:40:12',
    user: 'Hệ thống Trợ lý NQ Office AI',
    role: 'AI System',
    action: 'Trích xuất tự động Phiếu tham mưu',
    entity: 'Document & Tasks',
    entityId: 'DOC-2026-001',
    beforeContent: 'Dữ liệu văn bản thô scan PDF',
    afterContent: 'Trích xuất 3 nhiệm vụ độc lập, deadline 25/09/2026, dự thảo email giao việc',
    actorType: 'AI',
    approvedBy: 'Chờ Hiệu trưởng duyệt',
    ipAddress: 'Internal AI Engine',
  },
  {
    id: 'AUD-003',
    timestamp: '2026-09-06 10:28:45',
    user: 'TS. Đỗ Thị Lan (Hiệu trưởng)',
    role: 'HIEU_TRUONG',
    action: 'Duyệt & Giao việc từ Phiếu tham mưu',
    entity: 'Task Dispatch',
    entityId: 'TSK-001, TSK-002, TSK-005',
    beforeContent: 'Trạng thái: Chờ duyệt',
    afterContent: 'Trạng thái: Đã duyệt & Phát hành email giao việc tới cán bộ phụ trách',
    actorType: 'HUMAN',
    approvedBy: 'TS. Đỗ Thị Lan',
    ipAddress: '192.168.1.25',
  },
  {
    id: 'AUD-004',
    timestamp: '2026-09-05 14:10:00',
    user: 'Cô Phạm Thu Hà (Văn thư)',
    role: 'VAN_THU',
    action: 'Tiếp nhận văn bản số hóa',
    entity: 'Incoming Document',
    entityId: 'DOC-2026-003',
    beforeContent: 'Chưa có trong hệ thống',
    afterContent: 'Thêm công văn số 128/SGDĐT-VP, loại văn bản: Hỏa tốc',
    actorType: 'HUMAN',
    ipAddress: '192.168.1.42',
  },
];

export const THEME_PRESETS: Record<string, ThemeConfig> = {
  'Education Blue': {
    preset: 'Education Blue',
    primaryColor: '#0057B8',
    accentColor: '#2563EB',
    bgGradient: 'from-slate-50 via-blue-50/30 to-indigo-50/20',
    surfaceBg: '#FFFFFF',
    cardBg: '#FFFFFF',
    textColor: '#0F172A',
    isDark: false,
  },
  'Ocean Blue': {
    preset: 'Ocean Blue',
    primaryColor: '#0284C7',
    accentColor: '#0EA5E9',
    bgGradient: 'from-sky-50 via-cyan-50/40 to-blue-50/30',
    surfaceBg: '#FFFFFF',
    cardBg: '#FFFFFF',
    textColor: '#0C4A6E',
    isDark: false,
  },
  'School Brand': {
    preset: 'School Brand',
    primaryColor: '#1E3A8A', // Deep traditional navy of Ngo Quyen High School
    accentColor: '#D97706', // Traditional golden emblem accent
    bgGradient: 'from-amber-50/20 via-blue-50/30 to-slate-50',
    surfaceBg: '#FFFFFF',
    cardBg: '#FFFFFF',
    textColor: '#172554',
    isDark: false,
  },
  Emerald: {
    preset: 'Emerald',
    primaryColor: '#059669',
    accentColor: '#10B981',
    bgGradient: 'from-emerald-50/40 via-teal-50/30 to-slate-50',
    surfaceBg: '#FFFFFF',
    cardBg: '#FFFFFF',
    textColor: '#064E3B',
    isDark: false,
  },
  Purple: {
    preset: 'Purple',
    primaryColor: '#7C3AED',
    accentColor: '#8B5CF6',
    bgGradient: 'from-purple-50/40 via-fuchsia-50/20 to-slate-50',
    surfaceBg: '#FFFFFF',
    cardBg: '#FFFFFF',
    textColor: '#3B0764',
    isDark: false,
  },
  Sunset: {
    preset: 'Sunset',
    primaryColor: '#EA580C',
    accentColor: '#F97316',
    bgGradient: 'from-orange-50/40 via-amber-50/30 to-slate-50',
    surfaceBg: '#FFFFFF',
    cardBg: '#FFFFFF',
    textColor: '#431407',
    isDark: false,
  },
  Dark: {
    preset: 'Dark',
    primaryColor: '#3B82F6',
    accentColor: '#60A5FA',
    bgGradient: 'from-slate-950 via-slate-900 to-slate-950',
    surfaceBg: '#0F172A',
    cardBg: '#1E293B',
    textColor: '#F8FAFC',
    isDark: true,
  },
  Light: {
    preset: 'Light',
    primaryColor: '#2563EB',
    accentColor: '#3B82F6',
    bgGradient: 'from-gray-50 via-slate-50 to-zinc-50',
    surfaceBg: '#FFFFFF',
    cardBg: '#FFFFFF',
    textColor: '#18181B',
    isDark: false,
  },
};

export const INITIAL_AI_SETTINGS: AiSettings = {
  model: 'gemini-3.8-flash',
  temperature: 0.2,
  systemInstructions: `Bạn là trợ lý tham mưu số cho Ban Giám hiệu Trường THPT Ngô Quyền, Hải Phòng.
Tuân thủ nguyên tắc:
1. Đọc văn bản chính xác, bảo toàn pháp lý, không tự sáng tạo chi tiết sai lệch.
2. Đề xuất phân công công việc đúng tổ chuyên môn và đúng thẩm quyền của BGH/Tổ trưởng/Giáo viên.
3. Luôn yêu cầu sản phẩm đầu ra và minh chứng kiểm tra rõ ràng.
4. Tuân thủ cơ chế Human-in-the-loop: Mọi hành động quan trọng phải được người có thẩm quyền phê duyệt trước khi phát hành.`,
  automationLevel: 3, // Mức 3: AI tạo và chờ duyệt
  taskAssignmentRules: `Quy tắc phân công tự động:
- Lĩnh vực Chuyên môn dạy học, khảo thí, học sinh giỏi -> PHT Trần Văn Hùng & Các Tổ trưởng chuyên môn
- Lĩnh vực CSVC, an toàn trường học, trải nghiệm hướng nghiệp -> PHT Lê Thị Mai
- Lĩnh vực Tiếp nhận công văn, số hóa, văn thư lưu trữ -> Cô Phạm Thu Hà
- Lĩnh vực Hạ tầng CNTT, an toàn thông tin, phần mềm -> Thầy Bùi Minh Đức
- Lĩnh vực Dự toán, tài chính, thanh quyết toán -> Cô Hoàng Thị Thảo`,
  emailRules: `Quy tắc gửi email:
- Không gửi tự động ra ngoài khi chưa có xác nhận từ Ban Giám hiệu.
- Email phải có tiêu đề bắt đầu bằng [NQ OFFICE AI - THPT NGÔ QUYỀN].
- Nội dung email ghi rõ căn cứ công văn, nhiệm vụ, thời hạn và link truy cập phần mềm.`,
};

// Aliases for convenient importing across components
export const mockUsers = INITIAL_USERS;
export const mockDocuments = INITIAL_DOCUMENTS;
export const mockTasks = INITIAL_TASKS;
export const mockReports = INITIAL_REPORTS;
export const mockEmailDrafts = INITIAL_EMAIL_DRAFTS;
export const mockWorkDossiers = INITIAL_DOSSIERS;
export const mockAuditLogs = INITIAL_AUDIT_LOGS;
export const mockNotifications = INITIAL_NOTIFICATIONS;
export const defaultAiSettings = INITIAL_AI_SETTINGS;
export const mockAdvisorySheets = INITIAL_DOCUMENTS.map((d) => d.advisorySheet).filter(Boolean) as any[];

